### ISSUE TITLE
cant open window

### ISSUE THREAD

**Issue by dedpotato** [ErLinErYi/PlantsVsZombies#13]
Can't creat window
More info:
GLFWError #65542 Happen, WGL: The driver does not appear to support OpenGL

I'm trying to run the game in a windows VM

**Comment by ErLinErYi** [comment]
Maybe you need to update the graphics card driver and try again。



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 12, 2021 23:14 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ErLinErYi/PlantsVsZombies] cant open window (#13)




 
Can't creat window
 More info:
 GLFWError #65542 Happen, WGL: The driver does not appear to support OpenGL
 
I'm trying to run the game in a windows VM
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
