### ISSUE TITLE
顶级i9＋2080ti+16G内存提示帧数过低，给我强行关闭游戏了

### ISSUE THREAD

**Issue by wangchuanyes** [ErLinErYi/PlantsVsZombies#17]
实际上帧数并不低，不知道为什么会提示这个。关闭游戏设置中的高帧率选框后仍然会这样。

**Comment by ErLinErYi** [comment]
实际运行过程不卡吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月28日(周六) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ErLinErYi/PlantsVsZombies] 顶级i9＋2080ti+16G内存提示帧数过低，给我强行关闭游戏了 (Issue #17)




 
实际上帧数并不低，不知道为什么会提示这个。关闭游戏设置中的高帧率选框后仍然会这样。

**Comment by ErLinErYi** [comment]
你打开游戏自带帧率，它显示的是多少？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月28日(周六) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ErLinErYi/PlantsVsZombies] 顶级i9＋2080ti+16G内存提示帧数过低，给我强行关闭游戏了 (Issue #17)




 
实际上帧数并不低，不知道为什么会提示这个。关闭游戏设置中的高帧率选框后仍然会这样。

**Comment by wangchuanyes** [comment]
> 你打开游戏自带帧率，它显示的是多少？
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月28日(周六) 中午12:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [ErLinErYi/PlantsVsZombies] 顶级i9＋2080ti+16G内存提示帧数过低，给我强行关闭游戏了 (Issue #17 ) 实际上帧数并不低，不知道为什么会提示这个。 关闭游戏设置中的高帧率选框后仍然会这样。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Message ID: ***@***.***&gt;

2K分辨率高刷显示器，实际运行160多帧，一点都不卡。

**Comment by wangchuanyes** [comment]
重新安装了一遍 现在是锁定的60帧 好像可以玩了

**Comment by ErLinErYi** [comment]
可能是误检，下个版本修复。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月28日(周六) 中午12:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ErLinErYi/PlantsVsZombies] 顶级i9＋2080ti+16G内存提示帧数过低，给我强行关闭游戏了 (Issue #17)




  
你打开游戏自带帧率，它显示的是多少？
 ...
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年5月28日(周六) 中午12:02 收件人: @.&gt;; 抄送: @.&gt;; 主题: [ErLinErYi/PlantsVsZombies] 顶级i9＋2080ti+16G内存提示帧数过低，给我强行关闭游戏了 (Issue #17 ) 实际上帧数并不低，不知道为什么会提示这个。 关闭游戏设置中的高帧率选框后仍然会这样。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Message ID: @.&gt;
  
2K分辨率高刷显示器，实际运行160多帧，一点都不卡。
