### ISSUE TITLE
换了电脑CPU，主板存档丢了

### ISSUE THREAD

**Issue by Zombie2333** [ErLinErYi/PlantsVsZombies#18]
换了电脑CPU，主板后存档丢了，好像是一个说我修改存档的提示

**Comment by ErLinErYi** [comment]
一个存档只能在一台电脑上使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月5日(周日) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ErLinErYi/PlantsVsZombies] 换了电脑CPU，主板存档丢了 (Issue #18)




 
换了电脑CPU，主板后存档丢了，好像是一个说我修改存档的提示

**Comment by Zombie2333** [comment]
> 

那不优化一下么，我升级配件，原来存档就 不能用了，也太一刀切了。

**Comment by Immortal-Sty** [comment]
> 一个存档只能在一台电脑上使用
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月5日(周日) 中午11:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [ErLinErYi/PlantsVsZombies] 换了电脑CPU，主板存档丢了 (Issue #18) 换了电脑CPU，主板后存档丢了，好像是一个说我修改存档的提示 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

@ErLinErYi

***

如果我把存档的文件复制到其他电脑，其他电脑会拥有相同的存档吗？

如果会的话，能请问一下文件在哪吗？

**Comment by ErLinErYi** [comment]
不会，存档只能在原本电脑上使用，放到其他电脑无效。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月10日(周三) 凌晨0:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ErLinErYi/PlantsVsZombies] 换了电脑CPU，主板存档丢了 (Issue #18)




  
一个存档只能在一台电脑上使用
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年6月5日(周日) 中午11:48 收件人: @.&gt;; 抄送: @.&gt;; 主题: [ErLinErYi/PlantsVsZombies] 换了电脑CPU，主板存档丢了 (Issue #18) 换了电脑CPU，主板后存档丢了，好像是一个说我修改存档的提示 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
@ErLinErYi
 
 
如果我把存档的文件复制到其他电脑，其他电脑会拥有相同的存档吗？
 
如果会的话，能请问一下文件在哪吗？

**Comment by ErLinErYi** [comment]
这没办法，就是为了禁止互相共享存档的机制。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月5日(周日) 中午12:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ErLinErYi/PlantsVsZombies] 换了电脑CPU，主板存档丢了 (Issue #18)




   
那不优化一下么，我升级配件，原来存档就 不能用了，也太一刀切了。
