### ISSUE TITLE
[Linux] app doesn't work on Wine

### ISSUE THREAD

**Issue by nagayev** [ErLinErYi/PlantsVsZombies#6]
System info:
wine-5.0 (Ubuntu 5.0-3ubuntu1)
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 20
Release:        20
Codename:       ulyana
Command: `sudo wine LZELEYPVZ.exe`
Message:
`wine: Unhandled page fault on read access to FFFFFFFF at address 7BC68556 (thread 0044), starting debugger...`

**Comment by nagayev** [comment]
@ErLinErYi Update from windows
![изображение](https://user-images.githubusercontent.com/16555544/93385208-92ba5f00-f86e-11ea-937c-0aa98d2c30f2.png)

**Comment by ErLinErYi** [comment]
It is true that some computers can not run, I have tried to solve, but still can not completely solve. There is another version in the attachment. Try to run it. If there is still a problem, I don't know how to solve it. In addition, this is the repository of GitHub.https://github.com/ErLinErYi/PlantsVsZombies




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ErLinErYi/PlantsVsZombies"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 凌晨3:48
收件人:&nbsp;"ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送:&nbsp;"尔灵尔亿"<2117610943@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ErLinErYi/PlantsVsZombies] [Linux] app doesn't work on Wine (#6)





 
@ErLinErYi Update from windows
 
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

PlantsVsZombies.exe (80.79M, 2020年10月18日 16:49 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2d643037dc6f909cda4908491137514953540404000f57524852010f061a575f5c051d0f5352514b5251530200035504065d51563724633609055e434461103c0a09525e52444d031d01300a&t=exs_ftn_download&code=ed0777cf

**Comment by ErLinErYi** [comment]
Could not run before .dll file may be wrong. It has been fixed before. Try running it again if you have time. thank you.

**Comment by nagayev** [comment]
@ErLinErYi Okey. I'll check it tomorrow.

**Comment by nagayev** [comment]
@ErLinErYi Which version I can test?
You didn't realese any new versions.

**Comment by ErLinErYi** [comment]
You can try v1.2.0.3, the previous version of the file has been replaced.



---Original---

**Comment by nagayev** [comment]
@ErLinErYi 
Hello. I checked your game.
It is great! I want to help you with the translation. I don't know Chinese at all, but I know a bit English, and my native language is Russian.

**Comment by ErLinErYi** [comment]
That's great. The new version to be released in a few days will make it easier to change the translation work. In the attachment is a language JSON file that can be read directly by the new version of the program. You can add languages freely. I'll let you know when the new version is finished。Thank you for your attention to this program




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ErLinErYi/PlantsVsZombies"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 凌晨2:15
收件人:&nbsp;"ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送:&nbsp;"尔灵尔亿"<2117610943@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ErLinErYi/PlantsVsZombies] [Linux] app doesn't work on Wine (#6)





 
@ErLinErYi
 Hello. I checked your game.
 This is great! I want to help you with the translation. I don't know Chinese at all, but I know a little English, and my native language is Russian

**Comment by nagayev** [comment]
@ErLinErYi Hello. But where is the attachment? I don' see.
My another question is why you are using Github and Gitee, not only Github?
As I know Gitee is popular only among Chinese users.

**Comment by ErLinErYi** [comment]
I sent it by email. You can try checking it in your email.



---Original---

**Comment by nagayev** [comment]
@ErLinErYi I coudn't see it.
![изображение](https://user-images.githubusercontent.com/16555544/106015868-f3389300-60cf-11eb-8c60-73cccad5dcf2.png)

**Comment by ErLinErYi** [comment]
Well, it may not have been sent successfully. I'll send it to you again tomorrow.



---Original---

**Comment by ErLinErYi** [comment]
You can see that "Languagejson.rar " file?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ErLinErYi/PlantsVsZombies"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 晚上11:46
收件人:&nbsp;"ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送:&nbsp;"尔灵尔亿"<2117610943@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ErLinErYi/PlantsVsZombies] [Linux] app doesn't work on Wine (#6)





 
@ErLinErYi I coudn't see it.
 
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Language json.rar (14.8K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=23353536a6f4c6cbda180d4842300b1b0603050f07550952480d00055d1d0d000350185751515b1955065703525309520105020564213978045b524305575c140f465a584a4258466508&t=exs_ftn_download&code=e556d094

**Comment by nagayev** [comment]
@ErLinErYi Yes, I can see. So I would like suggest changing default language to English, 'cause understanding Chineese so complicated if you don't know this language.

**Comment by ErLinErYi** [comment]
Thank you for your advice。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ErLinErYi/PlantsVsZombies"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月28日(星期四) 下午2:26
收件人:&nbsp;"ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送:&nbsp;"尔灵尔亿"<2117610943@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ErLinErYi/PlantsVsZombies] [Linux] app doesn't work on Wine (#6)





 
@ErLinErYi Yes, I can see. So I would like suggest changing default language to English, 'cause understanding Chineese so complicated if you don't know this language.

**Comment by nagayev** [comment]
@ErLinErYi I'm finishing translation. So I'm awaiting new release.

**Comment by ErLinErYi** [comment]
Well, the new version will take a while. I can let you know when it's released.



---Original---

**Comment by nagayev** [comment]
@ErLinErYi Okey. I intend to send PR with readme on russian.
UPD: I have send it. You can merge it with squash.
